version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # or specify the runtime you need
    commands:
      - echo Installing NGINX
      - yum update -y
      - yum install nginx -y
      - mkdir -p /var/www/html
      - echo "NGINX installed and version $(nginx -v)"
  build:
    commands:
      - echo "Build started on $(date)"
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - '**/*'